# \u5F00\u53D1\u73AF\u5883\u914D\u7F6E
server:
  # \u670D\u52A1\u5668\u7684HTTP\u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u4E3A8080
  port: 9901
  servlet:
    # \u5E94\u7528\u7684\u8BBF\u95EE\u8DEF\u5F84
    context-path: /api/
  tomcat:
    # tomcat\u7684URI\u7F16\u7801
    uri-encoding: UTF-8
    # \u8FDE\u63A5\u6570\u6EE1\u540E\u7684\u6392\u961F\u6570\uFF0C\u9ED8\u8BA4\u4E3A100
    accept-count: 1000
    threads:
      # tomcat\u6700\u5927\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u4E3A200
      max: 800
      # Tomcat\u542F\u52A8\u521D\u59CB\u5316\u7684\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u503C10
      min-spare: 100

# \u65E5\u5FD7\u914D\u7F6E
logging:
  level:
    com.sso: info
    org.springframework: warn
    root: info
  path: ${user.home}/logs/sso-auth-center

# Spring\u914D\u7F6E
spring:
  #jackson\u65F6\u95F4\u683C\u5F0F\u5316\uFF08\u89E3\u51B3\u65F6\u533A\u95EE\u9898\uFF09
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # \u6587\u4EF6\u4E0A\u4F20
  servlet:
    multipart:
      # \u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-file-size:  10MB
      # \u8BBE\u7F6E\u603B\u4E0A\u4F20\u7684\u6587\u4EF6\u5927\u5C0F
      max-request-size:  20MB
  # \u670D\u52A1\u6A21\u5757
  devtools:
    restart:
      # \u70ED\u90E8\u7F72\u5F00\u5173
      enabled: true
  # redis \u914D\u7F6E
  redis:
    # \u5730\u5740  localhost
    host: 150.158.158.145
    # \u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u4E3A6379
    port: 6379
    # \u6570\u636E\u5E93\u7D22\u5F15
    database: 0
    # \u5BC6\u7801
    password: 123456
    # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
    timeout: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.158.145:3306/auth-center?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: njq123456

# \u81EA\u5B9A\u4E49\u914D\u7F6E
sys:
  config:
    captchaType: math
    tokenHeader: Authorization
    tokenSecret: abcdefghijklmnopqrstuvwxyz
    tokenExpireTime: 180
    authSsoSysCode: auth-center
    supperAdminUser: 1000|admin
    ssoLoginUrl: http://www.myauth.com:9528/login
    fileProfile: ${user.home}/files/upload


#\u963F\u91CC\u4E91OSS\u914D\u7F6E
aliyun:
  oss:
    file:
      # \u63A7\u5236\u53F0 - oss - \u70B9\u51FB\u5BF9\u5E94\u6876 - \u6982\u89C8 - \u5730\u57DF\u8282\u70B9
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tJL6rBvkrp8GggS8c34
      keysecret: X1UW2qAol87mSdVVmfSVQO1ClHPOIy
      bucketname: authplatform
